ScayTrase\MultiSiteBundle\Entity\Site:
    type: entity
    inheritanceType: SINGLE_TABLE
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
      name:
        type: string
      short_name:
        type: string
      description:
        type: text
      url:
        type: string
      email:
        type: string
      active:
        type: boolean
      logo:
        type: string
        nullable: true
