services:
  site.provider.doctrine:
    class: ScayTrase\MultiSiteBundle\Providers\DoctrineProvider
    abstract: true
    arguments:
    - @doctrine.orm.entity_manager

  site.filter_converter:
    class:    ScayTrase\MultiSiteBundle\ParamConverter\SiteParamConverter
    arguments: [@doctrine, @site.manager]
    tags:
    - { name: request.param_converter, priority: 2, converter: site_converter }

  site.provider.site_entity:
    class: ScayTrase\MultiSiteBundle\Providers\DoctrineProvider
    parent: site.provider.doctrine
    arguments:
    - 'MultiSiteBundle:Site'
    - url
    - { active: true }


  site.default_provider: @site.provider.site_entity


