services:
  site.fallback_factory:
    class: ScayTrase\MultiSiteBundle\Service\DefaultFallbackFactory

  site.manager:
    class: ScayTrase\MultiSiteBundle\Service\SiteManagerService
    arguments: [%site.maintenance_urls%, site.provider, @site.fallback_factory]
    tags:
        - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: -254 }

  site.empty_array_provider:
    class: ScayTrase\MultiSiteBundle\Providers\ConfigArrayProvider
    arguments:
    - []

  site.default_provider: @site.empty_array_provider

